### ISSUE TITLE
Feature:  Explain how to init a project

### ISSUE THREAD

**Issue by gaffo** [donuts-are-good/bearclaw#6]
The documentation references a few folders but doesn't say what should be in them or how to make them? is there an init command, or do I make the by hand? What's a good starting set of files?

**Comment by hollisticated-horse** [comment]
I believe you run the command once to generate the folder structure:

```
cd your_folder
```
either have the bearclaw executable in that folder, or set it up in your $PATH, to be able to call `./bearclaw` from any folder. 

Either way, run :
```
./bearclaw
```
and you get:

```bash
.
├── markdown
├── output
│   ├── about.html
│   └── posts.html
├── plugins
└── templates
```
with bearclaw 1.2.0alpha

**Comment by donuts-are-good** [comment]
thank you @hollisticated-horse for the explanation, I'm a bit surprised myself that I didn't include these instructions. @gaffo you make a good point, I should include better instructions, which is also touched on briefly in the issue here: https://github.com/donuts-are-good/bearclaw/issues/4

This can be completed this week during my breaks, maybe at the latest, this weekend. Thank you both for cluing me in on this, it's a big oversight on my part and I'm glad you brought it to my attention.

**Comment by hollisticated-horse** [comment]
I've made a PR to update the README.md, that adds the explanation I gave above. 

#15

**Comment by donuts-are-good** [comment]
PR Approved! Thank you everyone for your help! More additions to the Readme will follow
